set_property SRC_FILE_INFO {cfile:E:/Project/Personal/PoseEstimation/ZYNQPlatform/ZU7EG-TestDemo/zu01_led_test/zu01_led_test.srcs/constrs_1/new/sys_pin.xdc rfile:../../../zu01_led_test.srcs/constrs_1/new/sys_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports {LED_o[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {LED_o[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K24 [get_ports RSTn_i]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH22 [get_ports diff_clock_clk_p]
