set_property SRC_FILE_INFO {cfile:E:/Project/Doing/FpgaDev/FpgaDevDemo/demo210706_helloworld/demo210706_helloworld.srcs/constrs_1/new/system_pin.xdc rfile:../../../demo210706_helloworld.srcs/constrs_1/new/system_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH22 [get_ports diff_clk_p_i]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K24 [get_ports rst_n_i]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {led_o[0]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports {led_o[1]}]
